name: skilly
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.0.0
  google_sign_in: ^5.2.1

dev_dependencies:
  cloud_firestore: ^4.8.0
  firebase_auth: ^4.6.2
  firebase_core: ^2.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/
  uses-material-design: true
